In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('workout_raw_extracted.csv')

In [3]:
df.shape

(1035, 5)

In [4]:
df['date'] = pd.to_datetime(df['date'], dayfirst=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_27076\2130215706.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(df['date'], dayfirst=True)

In [5]:
df['exercise']= df['exercise'].str.title()

In [6]:
df.drop(columns=['time'],inplace=True)

In [7]:
df.head()

        date        exercise  weight  reps
0 2025-10-13  Dumbbell Press    20.0     9
1 2025-10-13  Dumbbell Press    20.0     7
2 2025-10-13  Dumbbell Press    20.0     6
3 2025-10-13  Barbell Rowing    20.0     7
4 2025-10-13  Barbell Rowing    20.0     7

In [8]:
df.isnull().sum()

date        0
exercise    0
weight      0
reps        0
dtype: int64

In [ ]:
prev_df=pd.read_excel('previous_training_log.xlsx')

In [10]:
prev_df.isnull().sum()

date            0
exercise        0
Muscle Group    0
weight          0
reps            0
dtype: int64

In [11]:
prev_df['exercise']= prev_df['exercise'].str.title()

In [12]:
prev_df.isna().sum()

date            0
exercise        0
Muscle Group    0
weight          0
reps            0
dtype: int64

In [13]:
prev_df.drop(columns=['Muscle Group'],inplace=True)

In [14]:
prev_df.head()

        date       exercise  weight  reps
0 2025-04-07         Squats    27.5    12
1 2025-04-07         Squats    30.0     9
2 2025-04-07         Squats    30.0     8
3 2025-04-07  Leg Extension    60.0    10
4 2025-04-07  Leg Extension    60.0     7

In [15]:
df.head()

        date        exercise  weight  reps
0 2025-10-13  Dumbbell Press    20.0     9
1 2025-10-13  Dumbbell Press    20.0     7
2 2025-10-13  Dumbbell Press    20.0     6
3 2025-10-13  Barbell Rowing    20.0     7
4 2025-10-13  Barbell Rowing    20.0     7

In [16]:
df = pd.concat([prev_df, df], ignore_index=True)

In [ ]:
bw_df=pd.read_excel('bodyweight_log.xlsx')

In [19]:
bw_df

          date  bodyweight
0   2025-04-06       70.60
1   2025-04-07       70.85
2   2025-04-08       70.30
3   2025-04-09       71.05
4   2025-04-10       70.70
..         ...         ...
304 2026-02-22       74.00
305 2026-02-23       74.10
306 2026-02-24       74.00
307 2026-02-25       73.90
308 2026-02-26       74.45

[309 rows x 2 columns]

In [20]:
df=pd.merge(df, bw_df, on='date', how='left')

In [21]:
df['exercise'].nunique()

97

In [22]:
df['exercise']=df['exercise'].str.lower()

In [23]:
df['exercise']=df['exercise'].str.strip()

In [24]:
standardise_exercise_name={
    'single arm overhead':'single arm overhead tricep extension',
    'tricep overhead single arm':'single arm overhead tricep extension',
    'maggrip pulldown':'mag grip lat pulldown',
    'tricep kick back':'tricep kickback',
    'tricep bar pushdown':'tricep pushdown',
    'normal lat pulldown':'lat pulldown',
    'incline press machine':'incline chest press machine',
    'ez bar pushdown':'tricep pushdown',
    'calf raises':'calf raise on LPM',
    'closegrip benchpress':'close grip bench press ez bar',
    'tricep rope overhead':'tricep overhead rope extension',
    'reverse curl':'reverse curls',
    'abs crunches':'cable crunches',
    'cable rows':'cable rowing',
    'tricep pushdown ez bar':'tricep pushdown',
    'cable lat pullover':'cable lat pullovers',
    'incline side lateral':'incline side lateral raises',
    'rdl':'dumbbell romanian deadlift',
    'incline press machine 2':'incline chest press machine 2',
    'reverse curl':'reverse curls',
    'preacher curl barbell':'preacher curls barbell',
    'close grip bench press ez bar':'closegrip benchpress ez bar',
    'tricep overhead':'tricep overhead bar extension'
}

In [25]:
df['exercise']=df['exercise'].replace(standardise_exercise_name)

In [26]:
df['exercise'].nunique()

86

In [31]:
for exercise in df['exercise'].unique():
    print(exercise)

squats
leg extension
lateral raises
cable rear delts
overhead press
preacher curls barbell
hammer curls
incline curls
incline dumbbell press
dumbbell press
single arm overhead tricep extension
tricep rope pushdown
barbell rowing
mag grip pulldown
chest supported dumbbell rows
single arm pulldown
chest supported lateral raises
closegrip benchpress ez bar
reverse curls
cable fly
preacher curl dumbbell
dumbbell press fly
v bar pulldown
bulgarian split squats
dumbbell fly
dumbbell romanian deadlift
rear delt fly cable
cable crunches
leg curl
cable lateral raises
face pull
closegrip dumbbell press
tricep kickback
deadlift
seated hammer curls
tricep overhead bar extension
rope hammer curls
tricep pushdown
ez bar curl
seated lateral raises
lat pulldown
incline chest press machine
cable lat pullovers
dumbbell rear delts fly
chest supported rear delts rows
leg press
barbell curls
cable rowing
incline dumbbell fly
landmine squats
calf raise on LPM
facepull
cable side lateral
close grip bench press ez bar
tricep overhead rope extension
pullups
dumbbell curls
incline hammer curls
cable wrist flexion
chest supported rows
spider curls
cable preacher curls
single arm hammer curls
incline side lateral raises
goblet squats
dumbbell rdl
machine lateral raises
reverse pec fly
mag grip lat pulldown
machine preacher curls
incline chest press machine 2
pecdec fly
machine abs crunches
closegrip benchpress straight bar
dumbbell calf raises
seated dumbbell calf raises
cable rdl
reverse lat pulldown
dumbbell hammer curls
benchpress
hamstring curls
incline rear delt fly
cable abs crunches
barbell rdl
single arm overhead extension
overhead skull crushee

In [28]:
df.loc[df['exercise']=='pullups','weight']=1

In [29]:
df['Volume']=df['weight']*df['reps']

In [30]:
df['Estimated 1RM'] = df['weight'] * (1 + df['reps'] / 30)

In [32]:
exercise_mapping = {

    # ---------------- LEGS ----------------
    'squats':'legs',
    'leg extension':'legs',
    'bulgarian split squats':'legs',
    'dumbbell romanian deadlift':'legs',
    'leg curl':'legs',
    'deadlift':'legs',
    'leg press':'legs',
    'landmine squats':'legs',
    'calf raise on LPM':'legs',
    'goblet squats':'legs',
    'dumbbell rdl':'legs',
    'barbell rdl':'legs',
    'cable rdl':'legs',
    'hamstring curls':'legs',
    'dumbbell calf raises':'legs',
    'seated dumbbell calf raises':'legs',

    # ---------------- CHEST ----------------
    'incline dumbbell press':'chest',
    'dumbbell press':'chest',
    'cable fly':'chest',
    'dumbbell press fly':'chest',
    'dumbbell fly':'chest',
    'incline chest press machine':'chest',
    'incline chest press machine 2':'chest',
    'incline dumbbell fly':'chest',
    'pecdec fly':'chest',
    'benchpress':'chest',

    # ---------------- BACK ----------------
    'barbell rowing':'back',
    'mag grip pulldown':'back',
    'mag grip lat pulldown':'back',
    'lat pulldown':'back',
    'reverse lat pulldown':'back',
    'v bar pulldown':'back',
    'single arm pulldown':'back',
    'pullups':'back',
    'cable lat pullovers':'back',
    'cable rowing':'back',
    'chest supported dumbbell rows':'back',
    'chest supported rows':'back',

    # ---------------- SHOULDERS ----------------
    'lateral raises':'shoulders',
    'cable rear delts':'shoulders',
    'rear delt fly cable':'shoulders',
    'dumbbell rear delts fly':'shoulders',
    'incline rear delt fly':'shoulders',
    'reverse pec fly':'shoulders',
    'face pull':'shoulders',
    'facepull':'shoulders',
    'cable lateral raises':'shoulders',
    'cable side lateral':'shoulders',
    'seated lateral raises':'shoulders',
    'machine lateral raises':'shoulders',
    'incline side lateral raises':'shoulders',
    'chest supported lateral raises':'shoulders',
    'chest supported rear delts rows':'shoulders',
    'overhead press':'shoulders',

    # ---------------- BICEPS ----------------
    'preacher curls barbell':'biceps',
    'preacher curl dumbbell':'biceps',
    'machine preacher curls':'biceps',
    'cable preacher curls':'biceps',
    'hammer curls':'biceps',
    'seated hammer curls':'biceps',
    'rope hammer curls':'biceps',
    'single arm hammer curls':'biceps',
    'incline hammer curls':'biceps',
    'incline curls':'biceps',
    'spider curls':'biceps',
    'dumbbell curls':'biceps',
    'barbell curls':'biceps',
    'ez bar curl':'biceps',
    'reverse curls':'biceps',

    # ---------------- TRICEPS ----------------
    'single arm overhead tricep extension':'triceps',
    'single arm overhead extension':'triceps',
    'tricep rope pushdown':'triceps',
    'tricep pushdown':'triceps',
    'tricep overhead rope extension':'triceps',
    'tricep overhead bar extension':'triceps',
    'tricep kickback':'triceps',
    'closegrip benchpress ez bar':'triceps',
    'close grip bench press ez bar':'triceps',
    'closegrip benchpress straight bar':'triceps',
    'closegrip dumbbell press':'triceps',
    'overhead skull crushee':'triceps',

    # ---------------- CORE ----------------
    'cable crunches':'core',
    'cable abs crunches':'core',
    'machine abs crunches':'core',

    # ---------------- FOREARMS ----------------
    'cable wrist flexion':'forearms'
}

In [33]:
df['Muscle Group']=df['exercise'].map(exercise_mapping)

In [34]:
df['Muscle Group'].value_counts()

Muscle Group
biceps       455
triceps      447
chest        374
back         353
legs         352
shoulders    331
core          47
forearms      12
Name: count, dtype: int64

In [35]:
df

,date,exercise,weight,reps,bodyweight,Volume,Estimated 1RM,Muscle Group
0,2025-04-07,squats,27.5,12,70.85,330.0,38.5,legs
1,2025-04-07,squats,30.0,9,70.85,270.0,39.0,legs
2,2025-04-07,squats,30.0,8,70.85,240.0,38.0,legs
3,2025-04-07,leg extension,60.0,10,70.85,600.0,80.0,legs
4,2025-04-07,leg extension,60.0,7,70.85,420.0,74.0,legs
...,...,...,...,...,...,...,...,...
2393,2026-02-26,incline curls,15.0,8,74.45,120.0,19.0,biceps
2394,2026-02-26,incline curls,15.0,6,74.45,90.0,18.0,biceps
2395,2026-02-26,dumbbell hammer curls,15.0,9,74.45,135.0,19.5,NaN
2396,2026-02-26,dumbbell hammer curls,15.0,9,74.45,135.0,19.5,NaN
2397,2026-02-26,dumbbell hammer curls,15.0,7,74.45,105.0,18.5,NaN

In [36]:
df['Relative Strength'] = df['Estimated 1RM'] / df['bodyweight']

In [37]:
df["Gym Type"] = np.where(
    (df['date'] >= '2025-12-13') & (df['date'] <= '2026-01-06'),
    'Soro Gym',
    'College Gym'
)

In [38]:
df[df['date']>='2025-12-13']

,date,exercise,weight,reps,bodyweight,Volume,Estimated 1RM,Muscle Group,Relative Strength,Gym Type
1743,2025-12-13,dumbbell rdl,25.0,7,69.30,175.0,30.833333,legs,0.444925,Soro Gym
1744,2025-12-13,dumbbell rdl,25.0,7,69.30,175.0,30.833333,legs,0.444925,Soro Gym
1745,2025-12-13,dumbbell rdl,25.0,7,69.30,175.0,30.833333,legs,0.444925,Soro Gym
1746,2025-12-13,leg press,52.5,10,69.30,525.0,70.000000,legs,1.010101,Soro Gym
1747,2025-12-13,leg press,52.5,10,69.30,525.0,70.000000,legs,1.010101,Soro Gym
...,...,...,...,...,...,...,...,...,...,...
2393,2026-02-26,incline curls,15.0,8,74.45,120.0,19.000000,biceps,0.255205,College Gym
2394,2026-02-26,incline curls,15.0,6,74.45,90.0,18.000000,biceps,0.241773,College Gym
2395,2026-02-26,dumbbell hammer curls,15.0,9,74.45,135.0,19.500000,NaN,0.261921,College Gym
2396,2026-02-26,dumbbell hammer curls,15.0,9,74.45,135.0,19.500000,NaN,0.261921,College Gym
2397,2026-02-26,dumbbell hammer curls,15.0,7,74.45,105.0,18.500000,NaN,0.248489,College Gym

In [39]:
df['Week']=df['date'].dt.isocalendar().week

In [40]:
df['Month']=df['date'].dt.strftime('%b')

In [41]:
df.columns=df.columns.str.upper()

In [42]:
df['EXERCISE']=df['EXERCISE'].str.title()
df['MUSCLE GROUP']=df['MUSCLE GROUP'].str.title()

In [43]:
df["PHASE"] = np.where(
    (df["DATE"] >= "2025-04-06") & (df["DATE"] <= "2025-06-14"),
    "Bulk",
    np.where(
        (df["DATE"] >= "2025-06-15") & (df["DATE"] <= "2025-11-11"),
        "Cut",
        np.where(
            df["DATE"] >= "2025-11-12",
            "Bulk",
            "Unknown"
        )
    )
)

In [44]:
df=df[['DATE','WEEK','MONTH','GYM TYPE','BODYWEIGHT','PHASE','EXERCISE','MUSCLE GROUP','WEIGHT','REPS','VOLUME','ESTIMATED 1RM','RELATIVE STRENGTH']]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DATE               2398 non-null   datetime64[ns]
 1   WEEK               2398 non-null   UInt32
 2   MONTH              2398 non-null   object
 3   GYM TYPE           2398 non-null   object
 4   BODYWEIGHT         2355 non-null   float64
 5   PHASE              2398 non-null   object
 6   EXERCISE           2398 non-null   object
 7   MUSCLE GROUP       2371 non-null   object
 8   WEIGHT             2398 non-null   float64
 9   REPS               2398 non-null   int64
 10  VOLUME             2398 non-null   float64
 11  ESTIMATED 1RM      2398 non-null   float64
 12  RELATIVE STRENGTH  2355 non-null   float64
dtypes: UInt32(1), datetime64[ns](1), float64(5), int64(1), object(5)
memory usage: 236.6+ KB

In [46]:
df[df['EXERCISE']=='Pullups']

,DATE,WEEK,MONTH,GYM TYPE,BODYWEIGHT,PHASE,EXERCISE,MUSCLE GROUP,WEIGHT,REPS,VOLUME,ESTIMATED 1RM,RELATIVE STRENGTH
1406,2025-10-27,44,Oct,College Gym,66.55,Cut,Pullups,Back,1.0,4,4.0,1.133333,0.017030
1407,2025-10-27,44,Oct,College Gym,66.55,Cut,Pullups,Back,1.0,3,3.0,1.100000,0.016529
1408,2025-10-27,44,Oct,College Gym,66.55,Cut,Pullups,Back,1.0,3,3.0,1.100000,0.016529
1451,2025-11-04,45,Nov,College Gym,65.30,Cut,Pullups,Back,1.0,4,4.0,1.133333,0.017356
1452,2025-11-04,45,Nov,College Gym,65.30,Cut,Pullups,Back,1.0,4,4.0,1.133333,0.017356
1453,2025-11-04,45,Nov,College Gym,65.30,Cut,Pullups,Back,1.0,3,3.0,1.100000,0.016845
1514,2025-11-11,46,Nov,College Gym,64.90,Cut,Pullups,Back,1.0,4,4.0,1.133333,0.017463
1515,2025-11-11,46,Nov,College Gym,64.90,Cut,Pullups,Back,1.0,3,3.0,1.100000,0.016949
1516,2025-11-11,46,Nov,College Gym,64.90,Cut,Pullups,Back,1.0,3,3.0,1.100000,0.016949

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DATE               2398 non-null   datetime64[ns]
 1   WEEK               2398 non-null   UInt32
 2   MONTH              2398 non-null   object
 3   GYM TYPE           2398 non-null   object
 4   BODYWEIGHT         2355 non-null   float64
 5   PHASE              2398 non-null   object
 6   EXERCISE           2398 non-null   object
 7   MUSCLE GROUP       2371 non-null   object
 8   WEIGHT             2398 non-null   float64
 9   REPS               2398 non-null   int64
 10  VOLUME             2398 non-null   float64
 11  ESTIMATED 1RM      2398 non-null   float64
 12  RELATIVE STRENGTH  2355 non-null   float64
dtypes: UInt32(1), datetime64[ns](1), float64(5), int64(1), object(5)
memory usage: 236.6+ KB

In [48]:
df.to_csv('feature_engineered_dataset.csv', index=False)